name: Update Visits

on:
      - main

jobs:
  update-visits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout:
  push:
    branches:
      - main

jobs:
  update-visits repository
        uses: actions/checkout@v:
    runs-on: ubuntu-latest
    steps:
      - uses2

      - name: Set visits variable
        run: echo: actions/checkout@v2
      - name: Update Visits
        run "visits=0" >> $GITHUB_ENV

      - name: Update badge in: |
          visits="0"
          echo $visits README
        run: |
          badge="![Visits]( > visits.txt
          echo "visits=$visits" >>https://img.shields.io/badge/Visits-21980-blue)"
          sed -i 's|!\[Visits\](https://img.shields.io/b $GITHUB_ENV
      - name: Update README
        run: |
          badge="![Visits](https://img.shields.ioadge/Visits-.*-blue)|'$badge'|' README.md