name: Update Visits

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/60 * * * *' # Runs every 60 minutes

jobs:
  update-visits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment visit counter
        id: increment
        run: |
          if [ ! -f visits.txt ]; then echo "0" > visits.txt; fi
          visits=$(cat visits.txt)
          visits=$((visits + 1))
          echo $visits > visits.txt
          echo "visits=$visits" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          visits=${{ env.visits }}
          badge="![Visits](https://img.shields.io/badge/Visits-${visits}-blue)"
          sed -i 's|!\[Visits\](https://img.shields.io/badge/Visits-.*-blue)|'"$badge"'|' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add visits.txt README.md
          git commit -m 'Update visits count'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main